name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy changes
        run: |
          # Replace this with your actual deployment commands
          npm install
          PORT=8000 npm run start
